spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service
    username: postgres
    password: Palash@1998

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9195